# Generated by Django 4.0.3 on 2022-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Email Already Exists'}, max_length=60, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('password2', models.CharField(max_length=20, verbose_name='Password2')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('roll_number', models.IntegerField(verbose_name='')),
                ('department', models.CharField(max_length=60, verbose_name='Department')),
            ],
        ),
    ]
