# Generated by Django 4.0.3 on 2022-05-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Email Already Exists'}, max_length=60, unique=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prerequisite', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=20)),
                ('registration_limit', models.IntegerField()),
                ('department', models.CharField(max_length=60, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Email Already Exists'}, max_length=60, unique=True, verbose_name='Email Address')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('roll_number', models.IntegerField(verbose_name='')),
                ('department', models.CharField(max_length=60, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='studentClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('student', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Email Already Exists'}, max_length=60, unique=True, verbose_name='Email Address')),
                ('department', models.CharField(max_length=60, verbose_name='Department')),
            ],
        ),
    ]
