# Generated by Django 4.0.3 on 2022-06-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacherclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherclass',
            old_name='student',
            new_name='teacher',
        ),
    ]
